### ISSUE TITLE
Deepnude no longer works

### ISSUE THREAD

**Issue by MatthewHKnight** [deep-man-yy/easydeepnude#11]
So, after reading that @deep-man-yy shut down his server this program no longer works is that right?
Was reading that on Telegram, would appear that way too because the program tried to access the internet when it was run, too lazy to run a Wireshark on why but I assume it has to do with it needing to process stuff via the server.

Also being that I am too lazy to look through the source why is a server even needed ?
And why was their no mention of needing one in the readme.

**Comment by deep-man-yy** [comment]
You have confused, what I have closed is the Telegram Bot since I was running on my own computer, it was just an experiment to see if it works and works perfectly (The bot).

EasyDeepNude needs Firewall permissions since he needs to create a local server to access the interface, none of this project is on a private server. All processing is done from the user's computer, otherwise it would not make sense to use CPU/GPU.

The creation of the private server is temporary since that is how NuxtJS works.

**Comment by MatthewHKnight** [comment]
It's okay girl I figured that all out not long after I made this post. By the way this version sucks balls https://thepiratebay.org/torrent/33728966/DeepNude_v2.0.0_Premium would be a lot easier for people to use.
